### ISSUE TITLE
When I refresh the page, I get a 404 error.

### ISSUE THREAD

**Issue by swallowcc** [Shyam-Chen/Vue-Starter#81]
Hello, I'm currently facing an issue with your project. After running "pnpm build" and placing the resulting "dist" files into nginx, I noticed that whenever I refresh the page, I get a 404 error. I'm not sure which step I may have missed in the setup. I would appreciate your response. Thank you very much.

**Comment by Shyam-Chen** [comment]
You need to configure Single Page Applications in Nginx, and I suppose the possible configuration could be:

```css
location / {
  try_files $uri /$uri /index.html;
}
```

I personally use [Caddy](https://caddyserver.com/), and below is my configuration:

https://github.com/Shyam-Chen/Vue-Starter/blob/main/Caddyfile#LL6C32-L6C32

**Comment by Shyam-Chen** [comment]
Here is an Nginx configuration I had a long time ago, sharing it with you:

```css
server {
  server_name ${NGINX_HOST};
  listen ${NGINX_PORT};

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /service-worker.js {
    add_header Cache-Control "max-age=0,no-cache,no-store,must-revalidate";
  }

  client_max_body_size 4G;
  keepalive_timeout 10;
}
```

If you still can't make it work successfully, you can consider downgrading the mode of Vue Router to `createWebHashHistory`. This issue pertains to Nginx and SPA (Single Page Application). I will close the issue.
